version: 0.2

env:
  variables:
    TARGET_TF_MODULE_DIR: <TARGET_TF_MODULE_DIR>

phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
      - unzip terraform_1.8.5_linux_amd64.zip
      - mv terraform /usr/local/bin/

  build:
    commands:
      - export CHDIR="$CODEBUILD_SRC_DIR_WORK/$TARGET_TF_MODULE_DIR"
      - terraform -chdir=$CHDIR init
      - terraform -chdir=$CHDIR fmt -check
      - terraform -chdir=$CHDIR validate
